import { getServerSession } from "next-auth";
import { Provider as ReduxProvider } from "react-redux";

import "./global.css";
import Navbar from "@/components/Navbar";
import { SessionProvider } from "@/components/SessionProvider";
import Sidebar from "@/components/Sidebar";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Login from "@/components/Login";
import ToastNotifications from "@/components/ToastNotifications";
import store from "@/features/store";
import PageContainer from "@/components/PageContainer";
import App from "@/components/App";

export const metadata = {
  title: "CoFixGPT",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <>
              <ToastNotifications />

              <main className="flex flex-col h-screen">
                <Navbar />
                {/* Navbars heigth is 5rem! */}
                <div className="flex h-[calc(100%-5rem)]">
                  <App>{children}</App>
                </div>
              </main>
            </>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
